package model;
// default package
// Generated 2017/3/5 上午 10:49:40 by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DetailPics generated by hbm2java
 */
@Entity
@Table(name = "DetailPics", catalog = "redLine")
public class DetailPicsBean implements java.io.Serializable {

	private Integer id;
	private String detail;
	private String pics;

	public DetailPicsBean() {
	}

	public DetailPicsBean(String detail, String pics) {
		this.detail = detail;
		this.pics = pics;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

 	public String getDetail() {
		return this.detail;
	}

 	
 	
	@Override
	public String toString() {
		return "DetailPicsBean [id=" + id + ", detail=" + detail + ", pics=" + pics + "]";
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

 	public String getPics() {
		return this.pics;
	}

	public void setPics(String pics) {
		this.pics = pics;
	}

}
