package model;

// default package
// Generated 2017/2/24 下午 02:20:27 by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MinorCategory generated by hbm2java
 */
@Entity
@Table(name = "minorCategory", schema = "RedLine")
public class MinorCategoryBean implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	private String category;
	private String item;

	public MinorCategoryBean() {
	}

	public MinorCategoryBean(String category, String item) {
		this.category = category;
		this.item = item;
	}

	
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

 	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

 	public String getItem() {
		return this.item;
	}

	public void setItem(String item) {
		this.item = item;
	}

	@Override
	public String toString() {
		return "MinorCategoryBean [id=" + id + ", category=" + category + ", item=" + item + "]";
	}

}
